-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgnbukJZ7/ADshA8qk
zx/+KfcaSvZRlwEpsJ7cgQdxb8igCgYIKoZIzj0DAQehRANCAAQEbMvwHQH6r3sS
PHtrjJAZ4x9GIaaTGT9F2lbrZAEv8ICbxA2S7k4OQPPdHWJ1/UvPcfNWls6Z75Le
bUXTrdnM
-----END PRIVATE KEY-----